// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.Sketcher = (function(_super) {
    __extends(Sketcher, _super);

    function Sketcher() {
      _ref = Sketcher.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Sketcher.prototype.initialize = function() {
      var _this = this;
      this.paths = [];
      $('canvas').on('mousedown', function(e) {
        _this.path = new paper.Path({
          strokeColor: '#E4141B',
          strokeWidth: 20,
          strokeCap: 'round'
        });
        return _this.paths.push(_this.path);
      });
      $('canvas').on('mousemove', function(e) {
        if (!_this.path) {
          return;
        }
        _this.path.add(new paper.Point(e.clientX, e.clientY));
        return _this.path.smooth();
      });
      return $('canvas').on('mouseup', function(e) {
        _this.path.strokeColor = '#38fa26';
        _this.path.smooth();
        return _this.path = null;
      });
    };

    return Sketcher;

  })(Backbone.Model);

}).call(this);
